 new-item -name "fileserver" -path "c:\" -itemtype "directory"
 set-location "c:\fileserver"
 $variable = import-csv "c:\employeelist.csv"
 new-item -itemtype "directory" -path "genghiskhan", "florencenightingale", "tychobrahe", "joannathemad", "ivantheterrible", "mariecurie", "joanofarc", "hypatiaofalexandria", "alexanderthegreat", "ottovonbismark", "alkindi", "boudica", "zhuyuanzhang", "gracehopper"

 new-item -itemtype "file" -path "genghiskhan/hello.txt"
 new-item -itemtype "file" -path "florencenightingale/hello.txt"
 new-item -itemtype "file" -path "tychobrahe/hello.txt"
 new-item -itemtype "file" -path "joannathemad/hello.txt"
 new-item -itemtype "file" -path "ivantheterrible/hello.txt"
 new-item -itemtype "file" -path "mariecurie/hello.txt"
 new-item -itemtype "file" -path "joanofarc/hello.txt"
 new-item -itemtype "file" -path "hypatiaofalexandria/hello.txt"
 new-item -itemtype "file" -path "alexanderthegreat/hello.txt"
 new-item -itemtype "file" -path "ottovonbismark/hello.txt"
 new-item -itemtype "file" -path "alkindi/hello.txt"
 new-item -itemtype "file" -path "boudica/hello.txt"
 new-item -itemtype "file" -path "zhuyuanzhang/hello.txt"
 new-item -itemtype "file" -path "gracehopper/hello.txt"

 "welcome genghiskhan!" | add-content "genghiskhan/hello.txt"
  "welcome florencenightingale!" | add-content "florencenightingale/hello.txt"
   "welcome tychobrahe!" | add-content "tychobrahe/hello.txt"
    "welcome joannathemad!" | add-content "joannathemad/hello.txt"
     "welcome ivantheterrible!" | add-content "ivantheterrible/hello.txt"
      "welcome mariecurie!" | add-content "mariecurie/hello.txt"
       "welcome joanofarc!" | add-content "joanofarc/hello.txt"
        "welcome hypatiaofalexandria!" | add-content "hypatiaofalexandria/hello.txt"
         "welcome alexanderthegreat!" | add-content "alexanderthegreat/hello.txt"
          "welcome ottovonbismark!" | add-content "ottovonbismark/hello.txt"
           "welcome alkindi!" | add-content "alkindi/hello.txt"
            "welcome boudica!" | add-content "boudica/hello.txt"
             "welcome zhuyuanzhang!" | add-content "zhuyuanzhang/hello.txt"
              "welcome gracehopper!" | add-content "gracehopper/hello.txt"
